packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@prisma/engines': true
  core-js-pure: true
  esbuild: true
  msw: true
  prisma: true
  puppeteer: true
  sharp: true

catalogs:
  default:
    lucide-react: ^1
    react: ^19
    react-dom: ^19
    recharts: ^3
    sonner: ^2
    typescript: ^6

    '@types/node': ^25
    '@types/react': ^19
    '@types/react-dom': ^19

    eslint: ^9
