name: Deploy to Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the project
        run: pnpm build
        env:
          NEXT_PUBLIC_DEMO_PASSWORD: ${{ vars.NEXT_PUBLIC_DEMO_PASSWORD }}
          NEXT_PUBLIC_AVATAR_URL: ${{ vars.NEXT_PUBLIC_AVATAR_URL }}

      - name: Package files
        run: |
          tar -czf release.tar.gz \
            apps/web/.next \
            apps/web/prisma \
            apps/web/prisma.config.ts \
            apps/web/package.json \
            apps/web/next.config.mjs \
            package.json \
            pnpm-lock.yaml \
            pnpm-workspace.yaml \
            packages \
            ecosystem.config.mjs

      - name: Upload to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'release.tar.gz'
          target: '/var/www/chi-flow'

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/chi-flow

            tar -xzf release.tar.gz

            export PUPPETEER_SKIP_DOWNLOAD=true
            pnpm install --frozen-lockfile

            cd ./apps/web
            pnpm prisma generate

            pnpm prisma migrate deploy

            cd ../../

            pm2 restart ecosystem.config.cjs || pm2 start ecosystem.config.cjs

            pm2 save

            rm release.tar.gz
