name: Deploy to Cloud

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the project
        run: pnpm build
        env:
          NEXT_PUBLIC_DEMO_PASSWORD: ${{ vars.NEXT_PUBLIC_DEMO_PASSWORD }}
          NEXT_PUBLIC_AVATAR_URL: ${{ vars.NEXT_PUBLIC_AVATAR_URL }}

      - name: Upload to Server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            apps/web/.next
            apps/web/public
            apps/web/package.json
            apps/web/next.config.ts
            apps/web/prisma
            packages
            package.json
            pnpm-lock.yaml
            pnpm-workspace.yaml
          target: '/var/www/chi-flow'

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd /var/www/chi-flow

            export NODE_ENV=production

            pnpm install --prod --frozen-lockfile

            pm2 restart chi-flow || \
            pm2 start "pnpm --filter web start -- --port 3002" \
              --name chi-flow

            pm2 save
